# Generated by Django 5.1.1 on 2024-09-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="movie_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="movie_poster",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="release_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
