# Generated by Django 5.1.1 on 2024-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_watchlist_movie_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="watched",
            field=models.BooleanField(default=False),
        ),
    ]
